north_creation_agency_sylius_klarna_gateway:
    cypher:
        key: '%env(PAYUM_CYPHER_KEY)%'
    checkout:
        uri: https://api.playground.klarna.com/checkout/v3/orders
        push_confirmation: https://api.playground.klarna.com/ordermanagement/v1/orders/{order_id}/acknowledge
