winzou_state_machine:
    sylius_payment:
        callbacks:
            # callbacks may be called before or after specified transitions, in the checkout state machine we've got callbacks only after transitions
            before:
                klarna_cancel:
                    on: ["cancel"]
                    do: ["@north_creation_agency_sylius_klarna_gateway.state_machine.cancel_payment", "cancel"]
                    args: ["object"]
            after:
                klarna_refund:
                    on: ["refund"]
                    do: ["@north_creation_agency_sylius_klarna_gateway.actions.refund", "refund"]
                    args: ["object"]
    sylius_shipment:
        callbacks:
            after:
                klarna_activate:
                    on: ["ship"]
                    do: ["@north_creation_agency_sylius_klarna_gateway.actions.activate", "activate"]
                    args: ["object.getOrder()"]
    sylius_order_checkout:
        callbacks:
            after:
                update_address:
                    on: ["address"]
                    do: ["@north_creation_agency_sylius_klarna_gateway.actions.update_address", "updateAddress"]
                    args: ["object"]
