parameters:
    sylius_klarna_gateway.checkout.klarna_secret: '%env(KLARNA_SECRET)%'
    sylius_klarna_gateway.checkout.uri: '%env(KLARNA_CHECKOUT_URI)%'
    
services:
    anders_bjorkland_sylius_klarna_gateway_plugin.klarna_checkout:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: ['AndersBjorkland\SyliusKlarnaGatewayPlugin\Payum\KlarnaCheckoutGatewayFactory']
        tags:
            - { name: payum.gateway_factory_builder, factory: klarna_checkout }
        
    anders_bjorkland_sylius_klarna_gateway_plugin.form.type.klarna_checkout_gateway_configuration:
        class: AndersBjorkland\SyliusKlarnaGatewayPlugin\Form\Type\KlarnaCheckoutGatewayConfigurationType
        arguments: ['@sylius.repository.payment_method']
        tags:
            - { name: sylius.gateway_configuration_type, type: klarna_checkout, label: 'Klarna Checkout' }
            - { name: form.type }
    
    anders_bjorkland_sylius_klarna_gateway_plugin.actions.capture:
        class: AndersBjorkland\SyliusKlarnaGatewayPlugin\Payum\Action\CaptureAction
        public: true
        arguments: [
            '@sylius.http_client', 
            '@parameter_bag', 
            '@sylius.tax_rate_resolver', 
            '@sylius.order_processing.shipping_charges_processor'
        ]
        tags:
            - { name: payum.action, factory: klarna_checkout, alias: payum.action.capture }
