north_creation_agency_sylius_klarna_gateway_push:
    path: /klarna-checkout/push
    methods: [POST]
    defaults:
        _controller: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Controller\KlarnaCheckoutController::handlePush
