# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    NorthCreationAgency\SyliusKlarnaGatewayPlugin\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    north_creation_agency_sylius_klarna_gateway.klarna_checkout:
        class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
        arguments: ['NorthCreationAgency\SyliusKlarnaGatewayPlugin\Payum\KlarnaCheckoutGatewayFactory']
        tags:
            - { name: payum.gateway_factory_builder, factory: klarna_checkout }
    
    north_creation_agency_sylius_klarna_gateway.form.type.klarna_checkout_gateway_configuration:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Form\Type\KlarnaCheckoutGatewayConfigurationType
        arguments: ['@north_creation_agency_sylius_klarna_gateway.cypher']
        tags:
            - { name: sylius.gateway_configuration_type, type: klarna_checkout, label: 'Klarna Checkout' }
            - { name: form.type }
    
    north_creation_agency_sylius_klarna_gateway.actions.capture:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Payum\Action\CaptureAction
        public: true
        arguments: [
            '@sylius.http_client',
            '@parameter_bag',
            '@north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever',
        ]
        tags:
            - { name: payum.action, factory: klarna_checkout, alias: payum.action.capture }
                
    north_creation_agency_sylius_klarna_gateway.actions.activate:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\StateMachine\ActivatePayment
        public: true
        
    north_creation_agency_sylius_klarna_gateway.actions.refund:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Payum\Action\RefundAction
        public: true
    
    north_creation_agency_sylius_klarna_gateway.api.order_management:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Api\OrderManagement
        public: true
        arguments: [
            '@parameter_bag',
            '@north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever',
            '@sylius.http_client',
        ]

    north_creation_agency_sylius_klarna_gateway.api.order_verifier:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Api\Verifier\OrderVerifier
        public: true
        arguments: [
            '@doctrine.orm.entity_manager',
            '@north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever',
            '@parameter_bag',
            '@sylius.http_client',
            '@north_creation_agency_sylius_klarna_gateway.api.order_management'
        ]

    north_creation_agency_sylius_klarna_gateway.cypher:
        class: Payum\Core\Bridge\Defuse\Security\DefuseCypher
        arguments: ['%north_creation_agency_sylius_klarna_gateway.cypher.key%']
        public: true

    north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Api\Authentication\BasicAuthenticationRetriever
        public: true
        arguments: [
            '@north_creation_agency_sylius_klarna_gateway.cypher'
        ]
    
    north_creation_agency_sylius_klarna_gateway.state_machine.cancel_payment:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\StateMachine\CancelPayment
        public: true
        arguments: [
            '@sylius.http_client',
            '@parameter_bag',
            '@north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever'
        ]
    
    north_creation_agency_sylius_klarna_gateway.state_machine.update_payment:
        class: NorthCreationAgency\SyliusKlarnaGatewayPlugin\StateMachine\UpdatePayment
        public: true
        arguments: [
            '@SM\Factory\Factory',
            '@north_creation_agency_sylius_klarna_gateway.api.order_verifier',
            '@parameter_bag'
        ]

    GuzzleHttp\ClientInterface: '@sylius.http_client'    
    NorthCreationAgency\SyliusKlarnaGatewayPlugin\Api\Authentication\BasicAuthenticationRetrieverInterface: '@north_creation_agency_sylius_klarna_gateway.basic_authentication_retriever'
    Payum\Core\Security\CypherInterface: '@north_creation_agency_sylius_klarna_gateway.cypher'
