Sylius\Component\Core\Model\Order:
    itemOperations:
        shop_klarna_widget:
            method: 'GET'
            path: 'shop/orders/{tokenValue}/klarna-widget'
            controller: NorthCreationAgency\SyliusKlarnaGatewayPlugin\Controller\KlarnaCheckoutController::getSnippet
            openapi_context:
                summary: Returns a Klarna checkout snippet
                responses:
                    200:
                        description: 'OK'
                        content:
                            application/json:
                                schema:
                                    type: object
                                    properties:
                                        snippet:
                                            type: string
                                            description: 'The Klarna checkout snippet'
                                            example: '<div id="klarna-checkout-container"></div>'
